# Primer on using vectors in python
 
This notebook is intended to show you the basics of linear algebra in python using the NumPy library. Why do we use a special library for linear algebra? Because python's own data types are multi-purpose while we want speed and efficiency. Numpy also provides a multitude of operations that are only relevant for us who use python for mathematics heavy applications.

In [ ]:
import numpy as np

## Chapter 1.1 exercises

Vectors are defined by making a list with numbers and then letting numpy transforming it into its own data format. Note that vectors in numpy do not differentiate between horisontal or vertical order by default (as we do in the lectures).

In [ ]:
u = np.asarray([1, -3, 6, 0])
v = np.asarray([1, -2, 2, 5])
u, v

(array([ 1, -3,  6,  0]), array([ 1, -2,  2,  5]))

The output from the statement on the last code line of a cell will be printed. This does not affect whatever you were doing in the code. It's simply a way of giving feedback to the programmer (you).

Let's define a vector and output its content.

In [ ]:
q = np.asarray([1, 2, 3])
q

array([1, 2, 3])

Now for the python version of the matlab (another programming language) exercises. Try these statements and see what they do:

1. u + v
2. 2u
3. 2∗u
4. s = u/2
5. s
6. u/v
7. u[2]
8. t = u/u[2]
9. t
10. s = np.arange(3, 9)
11. t = np.arange(1, 2.8, .2)
12. len(t)

In [ ]:
u+v

array([ 2, -5,  8,  5])

### L13: Exercise generator

Addition and scalar multiplication

In [ ]:
n_dim = np.random.randint(2, 3)
p = np.random.randint(-9, 9, size=n_dim)
q = np.random.randint(-9, 9, size=n_dim)
a = np.random.randint(-9, 9)
b = np.random.randint(-9, 9)
print("%i*%s + %i*%s = ?" % (a, tuple(p), b, tuple(q)))
print()
print("Answer: %s" % (repr(tuple((a*p+b*q)))))

-1*(7, -6) + -6*(-6, -2) = ?

Answer: (29, 18)


Systems of equations

In [ ]:
n_dim = np.random.randint(2, 4)
variables = "xyz"
coefficients = np.asarray([np.random.randint(-9, 9, size=n_dim+1) for i in range(n_dim)])
print("System of equations:")
for j, coeffs in enumerate(coefficients):
  print("\t"+" + ".join(["%i*%s" % (coeffs[j], variables[j]) for j in range(len(coeffs)-1) if coeffs[j] != 0]), end="")
  print(" = %i" % coeffs[-1])
print()
print("Solution (approximate, with rounding errors):")
for i, a in enumerate(np.linalg.solve(coefficients[:, :-1], coefficients[:, -1])):
  print("\t%s=%.3f" % (variables[i], a))


System of equations:
	-8*z = 5
	-3*x + 4*y + 5*z = 6
	-1*x + 7*y = 5

Solution (approximate, with rounding errors):
	x=-2.581
	y=0.346
	z=-0.625


Length using euclidean distance

In [ ]:
n_dim = np.random.randint(2, 5)
p = np.random.randint(-9, 9, size=n_dim)
q = np.random.randint(-9, 9, size=n_dim)
print("|%s - %s| = ?" % (tuple(p), tuple(q)))
print()
print("Answer (approximate, with rounding errors): |%s| = %.4f" % (repr(tuple(p-q)), np.linalg.norm(p-q)))

|(-1, 2, 2, -9) - (3, 2, 0, 2)| = ?

Answer (approximate, with rounding errors): |(-4, 0, 2, -11)| = 11.8743


## Chapter 1.2

In [ ]:
from numpy.linalg import norm