In [1]:
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

## 1.1

In [6]:
u = np.vstack([1, -3, 6, 0])
v = np.vstack([1, -3, 6, 0])

In [7]:
print(u+v)

[[ 2]
 [-6]
 [12]
 [ 0]]


## 1.2

In [21]:
n = 5

r = np.random.rand(n, 1)
u = np.ones((n, 1))
v = np.zeros((n, 1))
v[0] = 1

from numpy.linalg import norm

def dot(u, v):
    return u.ravel().dot(v.ravel())

print(r)
print(u)
print(v)
print(norm(u))
print(dot(u, v))


[[0.12010266]
 [0.97511892]
 [0.68234085]
 [0.47113197]
 [0.7300791 ]]
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]]
2.23606797749979
1.0
